kurento:
  - ip: ""
    url: ws://HOST/kurento
kurentoStartupRetries: Infinity
webhookURL: WEBHOOK_URL
hostAddress: HOST_ADDRESS
enableConnHealthcheck: true
connHealthCheckInterval: 30000

freeswitch:
  enabled: true
  eslIP: '127.0.0.1'
  eslPort: 8021
  eslPassword: 'ClueCon'
